basePath: /v1
definitions:
  controllers.DomainInfoResult:
    properties:
      domain:
        type: string
      hosts:
        items:
          $ref: '#/definitions/controllers.HostResult'
        type: array
      tenants:
        items:
          type: string
        type: array
      uuid:
        type: string
    type: object
  controllers.DomainListResult:
    properties:
      domains:
        items:
          $ref: '#/definitions/controllers.DomainResult'
        type: array
    type: object
  controllers.DomainRequest:
    properties:
      domain:
        type: string
      tenants:
        items:
          type: string
        type: array
    type: object
  controllers.DomainResult:
    properties:
      domain:
        type: string
      tenants:
        items:
          type: string
        type: array
      uuid:
        type: string
    type: object
  controllers.DomainUpdateRequest:
    properties:
      tenants:
        items:
          type: string
        type: array
    type: object
  controllers.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  controllers.HostRequest:
    properties:
      address:
        type: string
      hostname:
        type: string
    type: object
  controllers.HostResult:
    properties:
      address:
        type: string
      hostname:
        type: string
      uuid:
        type: string
    type: object
host: 172.28.21.40:8080
info:
  contact:
    email: support@hogehoge.hoge
    name: Hogehoge
    url: http://hoge.hogehoge.hoge/support
  description: REST API to manage domain info on CoreDNS
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: CoreDNS API
  version: "1.0"
paths:
  /v1/domains:
    get:
      description: List domains from coredns
      parameters:
      - description: Tenant UUID to set access control
        in: header
        name: Tenant
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.DomainListResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: List domains
      tags:
      - Domain
    post:
      consumes:
      - application/json
      description: Add new domain to coredns
      parameters:
      - description: Request body parameter with json format
        in: body
        name: domain
        required: true
        schema:
          $ref: '#/definitions/controllers.DomainRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.DomainInfoResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Add new domain
      tags:
      - Domain
  /v1/domains/{domain_uuid}:
    delete:
      description: Delete new domain to coredns
      parameters:
      - description: Tenant UUID to set access control
        in: header
        name: Tenant
        required: true
        type: string
      - description: Target domain's UUID
        in: path
        name: domain_uuid
        required: true
        type: string
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Delete domain
      tags:
      - Domain
    get:
      description: Get domain from coredns
      parameters:
      - description: Tenant UUID to set access control
        in: header
        name: Tenant
        required: true
        type: string
      - description: Target domain's UUID
        in: path
        name: domain_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.DomainInfoResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Get domain
      tags:
      - Domain
    patch:
      description: Update domain info
      parameters:
      - description: Tenant UUID to set access control
        in: header
        name: Tenant
        required: true
        type: string
      - description: Target domain's UUID
        in: path
        name: domain_uuid
        required: true
        type: string
      - description: Request body parameter with json format
        in: body
        name: domain
        required: true
        schema:
          $ref: '#/definitions/controllers.DomainUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.DomainInfoResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Update domain
      tags:
      - Domain
  /v1/domains/{domain_uuid}/hosts:
    get:
      description: List hosts from domain
      parameters:
      - description: Tenant UUID to set access control
        in: header
        name: Tenant
        required: true
        type: string
      - description: Target domain's UUID
        in: path
        name: domain_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.DomainInfoResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: List hosts
      tags:
      - Host
    patch:
      consumes:
      - application/json
      description: Update host info
      parameters:
      - description: Tenant UUID to set access control
        in: header
        name: Tenant
        required: true
        type: string
      - description: Target domain's UUID
        in: path
        name: domain_uuid
        required: true
        type: string
      - description: Request body parameter with json format
        in: body
        name: host
        required: true
        schema:
          $ref: '#/definitions/controllers.HostRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/controllers.DomainInfoResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Update host
      tags:
      - Host
    post:
      consumes:
      - application/json
      description: Add new host to domain
      parameters:
      - description: Tenant UUID to set access control
        in: header
        name: Tenant
        required: true
        type: string
      - description: Target domain's UUID
        in: path
        name: domain_uuid
        required: true
        type: string
      - description: Request body parameter with json format
        in: body
        name: host
        required: true
        schema:
          $ref: '#/definitions/controllers.HostRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/controllers.DomainInfoResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Add new host
      tags:
      - Host
  /v1/domains/{domain_uuid}/hosts/{host_uuid}:
    delete:
      description: Delete host info
      parameters:
      - description: Tenant UUID to set access control
        in: header
        name: Tenant
        required: true
        type: string
      - description: Target domain's UUID
        in: path
        name: domain_uuid
        required: true
        type: string
      - description: Target host's UUID
        in: path
        name: host_uuid
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/controllers.DomainInfoResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Delete host
      tags:
      - Host
    get:
      description: Get host info
      parameters:
      - description: Tenant UUID to set access control
        in: header
        name: Tenant
        required: true
        type: string
      - description: Target domain's UUID
        in: path
        name: domain_uuid
        required: true
        type: string
      - description: Target host's UUID
        in: path
        name: host_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.DomainInfoResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.HTTPError'
      summary: Get host
      tags:
      - Host
swagger: "2.0"
