// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package infrastructure

import (
	"coredns_api/internal/infrastructure"
	"coredns_api/internal/interface/repository"
	"coredns_api/internal/usecase"
	"coredns_api/pkg/interface/controllers"
)

// Injectors from wire.go:

func InitializeTenantController() *controllers.TenantController {
	iFilesystem := infrastructure.NewFilesystem()
	iFilesystemRepository := repository.NewFileRepository(iFilesystem)
	tenantInteractor := usecase.NewTenantInteractor(iFilesystemRepository)
	tenantController := controllers.NewTenantController(tenantInteractor)
	return tenantController
}
